### ISSUE TITLE
uglify-js missing from package.json

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2087]
```
17:30:37 webapp.1 | Running "browserify:dist" (browserify) task
17:30:42 webapp.1 | Fatal error: Cannot find module 'uglify-js'
```

# Steps to recreate

```bash
rm -rf node_modules/uglify-js && npm install && grunt browserify
```

**Comment by garethbowen** [comment]
The problem here is uglify-js is a transitive dependency and it looks like your npm didn't check it existed on npm install. What version of npm are you using? I can't reproduce this with npm v3.6.

The problem here is it could happen with every transitive dependency of which we have hundreds and I wouldn't want to have to include all of them in the package.json.

I think we should revert this commit as I think it'll only help with old versions of npm and when a transitive dependency is deleted. If you wipe the entire node_modules dir it should work as expected.

**Comment by garethbowen** [comment]
It's supposedly fixed in 3.0: https://github.com/npm/npm/issues/1341

**Comment by alxndrsn** [comment]
```$ npm --version
2.14.2```

Sorry about this - I'll upgrade.

**Comment by alxndrsn** [comment]
Reverted.
