### ISSUE TITLE
SMS from medic-gateway do not appear in Messages tab

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2530]
On 2.x, SMS from `medic-gateway`, submitted via `/api/sms`, do not appear in the _Messages_ tab.

**Comment by waqar-ah** [comment]
medic-gateway app shows `URL is not responding in the expected way`

URL is `http://admin:pass@localhost:5988/medic/_design/medic/_rewrite/add`

**Comment by waqar-ah** [comment]
Also it shows this error   `WARN sms-gateway [TypeError: callback is not a function]`   in api  running log

**Comment by garethbowen** [comment]
Yes this is broken - the "sms-gateway" controller calls a `create` function on the "records" controller with the wrong number of parameters. I'll prioritise this now.

**Comment by garethbowen** [comment]
Issues raised for other problems found while debugging:

* Better error handling: #2617
* Use bulk docs: #2618

**Comment by garethbowen** [comment]
### Code review

Two PRs:

- [api](https://github.com/medic/medic-api/pull/93): Lots of refactoring, renaming, reorganising. It might be easiest to review commit by commit rather than a full diff...
- [webapp](https://github.com/medic/medic-webapp/pull/2619): Mostly just adding the e2e testing. Also updated the update function to check for scheduled_tasks not just tasks, and added translation and styling for the new states.

**Comment by alxndrsn** [comment]
Comments on PRs

**Comment by abbyad** [comment]
Works well in v2.9, moving to Ready
