### ISSUE TITLE
Contact names not showing in messages tab

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2545]
On latest `master`, I am not seeing the names of contacts in the _Messages_ tab.  Instead, the errors:

> `inbox.js:9 TypeError: Cannot read property 'messages' of null`

and 

> `inbox.js:9 Error fetching contact conversation TypeError: Cannot read property 'messages' of null`

appear in the console:

<img width="1280" alt="screen shot 2016-07-22 at 14 44 01" src="https://cloud.githubusercontent.com/assets/191496/17057555/08fb5ee0-501b-11e6-80c1-c7b5cca7e772.png">

**Comment by alxndrsn** [comment]
On refreshing the page, the contact names are still not displayed, but there are no errors in the console.

**Comment by garethbowen** [comment]
It looks like the data has been broken. On the original server one particular record (ID: 84455637f030249037d5b599a0cc290c) looks like this...

```
{ ..., tasks: [ {
  messages: [ {
    facility: {
      ...,
      contact: {
        name: "Some Real Name"
        phone: "+55555555..."
      }
    }
  } ]
} ] }
```

On the `-testing` server it looks like this...

```
{ ..., tasks: [ {
  messages: [ {
    contact: {
      db_name: medic,
      doc_count: 3688,
      ...
    }
  } ]
} ] }
```

The one on the testing server just looks like the db info response which is bizarre and obviously useless.

**Comment by garethbowen** [comment]
Unhandled case. It'd be good to clone the db and try and migration again.

**Comment by abbyad** [comment]
Works in v2.9, moving to Ready
