### ISSUE TITLE
Cannot open add family form in 2.13.0-beta.13

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3891]
Seen on lg.dev logged in as demo1 (password in 1password).

When trying to load the add family form, I get the following error in the console:
![image](https://user-images.githubusercontent.com/1286381/30288777-c453c898-96de-11e7-8aa1-a10d31f73e18.png)

This form has worked on previous versions.

**Comment by garethbowen** [comment]
Reproduced locally. The unminified error is:

```
Error loading contact form. Error: ["FormLogicError: Could not evaluate: date(concat(string(../ephemeral_years),'-',if(../ephemeral_months<10, concat('0',string(../ephemeral_months)), ../ephemeral_months),'-',string(format-date-time(today(), \"%d\")))), message: arg.v.indexOf is not a function"]
    at enketo.js:251
    at processQueue (angular.js:16832)
    at angular.js:16876
    at Scope.$digest (angular.js:17971)
    at angular.js:18200
    at completeOutstandingRequest (angular.js:6274)
    at angular.js:6554
```

Give the message I think it's coming from the `openrosa-xpath-evaluator` module.

`master` appears unaffected so I suspect it's been fixed in one of the recent commits to the `openrosa-xpath-evaluator`, possibly [this one](https://github.com/medic/medic-webapp/commit/d537408c87c8ece29bcc4dab86a4af6bc2fc6bc2). @alxndrsn Does this ring a bell? Is it safe to upgrade our 2.13.x branch to 1.3.2 or 1.4.1?

**Comment by alxndrsn** [comment]
```
date(
  concat(
    string(../ephemeral_years),
    '-',
    if(
      ../ephemeral_months<10,
      concat(
        '0',
        string(../ephemeral_months)
      ),
      ../ephemeral_months
    ),
    '-',
    string(format-date-time(today(), \"%d\"))
  )
)
```
This looks like a very complicated way to format a date.

**Comment by alxndrsn** [comment]
Seems to work on `master`.

**Comment by alxndrsn** [comment]
Seems to work on `2.13.0-beta.13` too.  I can't recreate this.

@garethbowen on your machine, what's the value of `arg.v` when the `Error` is thrown?

**Comment by garethbowen** [comment]
Happens for me every time on `2.13.x` - did you npm install to get the right version of the module?

This is the value for `arg` that's causing the issue: `{t: "str", v: 10}`. I think either the `t` should be "num" or the `v` should be a string.

**Comment by garethbowen** [comment]
Bumping the dependency to 1.3.2 fixed the issue. Code review please @alxndrsn 

I typoed the issue number in the initial commit so if you do a merge fix that before you merge, or leave the merge to me and I'll do it, thanks!

This only needs to go in `2.13.x` not in `master` as `master` already uses a later dependency.

**Comment by alxndrsn** [comment]
👍 

This still looks like a very complicated way to format a date.

**Comment by sglangevin** [comment]
@alxndrsn if you have a better suggestion for how to format a date in this format (`YYYY-MM-DD`) let me know. I don't think formatting in that way is supported, though I could have misread the date formatting documentation. The main issue, if I remember right, was getting the 2-digit month for months that are less than 10.

**Comment by alxndrsn** [comment]
This works for me:
```
format-date(/path/to/date, '%Y-%m-%d')
```

**Comment by sglangevin** [comment]
Right, but I don't have a path to a full date because I just have a number of months and a number of years. So I have to get the day of today's date to even create the date in the first place.

**Comment by alxndrsn** [comment]
Ah, sorry!  I'd expect the following to work, but as you've found it doesn't like parsing dates with single-digit values in:
```
date(
  concat(
    ../ephemeral_years
    '-',
    ../ephemeral_months,
    '-',
    format-date-time(today(), '%d')
  )
)
```
Hopefully this will be fixed in the future!

**Comment by alxndrsn** [comment]
Parsing dates with single-digit month or day values should be fixed in linked PR.

**Comment by alxndrsn** [comment]
I couldn't recreate the supposed xpath bug in version 1.3.0 of the evaluator, so it may not actually be fixed by the upgrade.  Let me know if similar is seen again!

**Comment by garethbowen** [comment]
The single-digit month and day change was incompatible with `2.13.x` so I've rolled it back. If this is needed before `2.14.x` let me know and I can get it working.

**Comment by sglangevin** [comment]
Working well in 2.13.0-beta.15. Moving to ready.
