### ISSUE TITLE
Production installation of api fails with missing dependency

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3963]
When upgrading beta.dev to 2.14.0-beta.1 it started throwing this error.

```
2017-10-13T16:42:34.750Z - error: module.js:471                 
    throw err;                                                 
    ^                                                                                                                            
Error: Cannot find module 'buffer-shims'                       
    at Function.Module._resolveFilename (module.js:469:15)     
    at Function.Module._load (module.js:417:25)                 
    at Module.require (module.js:497:17)                       
    at require (internal/module.js:20:19)                       
    at Object.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/concat-stream/node_modules/readabl
    at Module._compile (module.js:570:32)                       
    at Object.Module._extensions..js (module.js:579:10)         
    at Module.load (module.js:487:32)                           
    at tryModuleLoad (module.js:446:12)                         
    at Function.Module._load (module.js:438:3)          
```

Upon investigation it was found that `npm install --production` doesn't install this module which is required by our production code.

beta.dev is running a pre-package-lock version of npm which may be the issue.

Apparently @derickl ran into this running in vmware too.

**Comment by garethbowen** [comment]
What a complete mess this is...

I switched my local npm to a similar version as in production and couldn't quite replicate this issue but did find a reference to "buffer-shims" buried deep in the minified code of the `ajv` module. The relevant part of the dependency tree is...

```
├─┬ nano@6.4.2
│ ├─┬ cloudant-follow@0.13.0
│ │ └─┬ request@2.81.0
│ │   │ ├── ajv@4.11.8
```

In the package-lock we lock nano down to 6.4.0 which has a completely different dependency graph that doesn't include ajv at all. So anyone one node 8 will get a working system and anyone on node 6 will get a broken one.

I'm unsure why alpha.dev was unaffected but the nano in its node_modules is still 6.4.0. I suspect it was supplied by the npm cache on alpha.dev but the cache on beta.dev was empty for some reason. Either that or the gardener installation process is non-deterministic (also quite likely).

I ran the following command to install 6.4.0 on beta.dev and the server came up right away.

```
/srv/software/medic-core/v1.6.1/x64/bin/node /srv/software/medic-cor
e/v1.6.1/x64/lib/node_modules/npm/cli.js install nano@6.4.0
```

I recommend anyone else affected by this issue run the above command.

For now I'm proposing we fix the nano dependency to `6.4.0` (instead of the current `^6.4.0`) which should work around the issue for now.

This will be fixed permanently by switching to horticulturalist (coming as part of medic-webapp v3) which will pre-package all the dependencies to get deterministic installs.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
Yikes, what a fiasco. Thanks for looking into it.

Merged.

**Comment by sglangevin** [comment]
@ngaruko what is the status of AT on this issue?

**Comment by sglangevin** [comment]
After upgrading standard.dev from 2.13.0-beta.22 to 2.14.0-beta.2, I ran into what appears to be the same issue.

```
2017-11-02T21:48:17.505Z - error: module.js:471                                                                                                      
    throw err;                                                                                                                                       
    ^                                                                                                                                                
                                                                                                                                                     
Error: Cannot find module 'buffer-shims'                                                                                                             
    at Function.Module._resolveFilename (module.js:469:15)                                                                                           
    at Function.Module._load (module.js:417:25)                                                                                                      
    at Module.require (module.js:497:17)                                                                                                             
    at require (internal/module.js:20:19)                                                                                                            
    at Object.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/m
    at Module._compile (module.js:570:32)                                                                                                            
    at Object.Module._extensions..js (module.js:579:10)                                                                                              
    at Module.load (module.js:487:32)                                                                                                                
    at tryModuleLoad (module.js:446:12)                                                                                                              
    at Function.Module._load (module.js:438:3)
```

**Comment by alxndrsn** [comment]
Certainly seems like package-lock is a good idea :¬)

**Comment by garethbowen** [comment]
@alxndrsn We have a package-lock. The problem is because we're running an old npm it ignores it. If we also included a shrinkwrap I think it'd work.

**Comment by alxndrsn** [comment]
Sorry, my comment was ambiguous.  I meant I'm glad that for future builds we'll be able to rely on package lock to prevent this kind of problem.

**Comment by SCdF** [comment]
I've renamed `package-lock.json` to `npm-shrinkwrap.json` in the 2.14.x branch. Once we cut a new beta we can see if this works properly, and if it does we'll do that for 2.15 as well

**Comment by sglangevin** [comment]
Working well in 2.14.0-beta.3. I was able to upgrade successfully from 2.13.0 to 2.14-0.beta.3.

**Comment by sglangevin** [comment]
I ran into this issue again when upgrading from 2.13.0-beta.22 to 2.14.0-beta.4 and the command above didn't solve the issue. Any ideas? I had to replace v1.6.1 with v1.7.1 due to the recent CouchDB upgrade, but I'm assuming that shouldn't affect anything, right?

**Comment by SCdF** [comment]
So my understanding ( @henokgetachew confirm ) is that all servers are now on Node 6.8.5, which should actually be enough to understand. I wonder if Gardener uses a different internal version, and that's causing issues?

I think this is going to be a giant endless pain until 3.0 I imagine. The next thing we can try is to manually include buffer-shims in our package.json.

@sglangevin is this error reproducible for you, or is it only on some servers?

**Comment by henokgetachew** [comment]
@SCdF Node 6.9.5 is the version we use.

**Comment by SCdF** [comment]
@garethbowen presumably we're going to have the same problem in 2.15 right? Presumably we should forward port this…

**Comment by garethbowen** [comment]
@SCdF Yes this will need to be forward ported until we get to 3.0.0

**Comment by SCdF** [comment]
@sglangevin let me know if this works and if so I'll forward port to master

**Comment by sglangevin** [comment]
Worked perfectly on my test upgrade (from 2.13.0 to 2.14.0-beta.5).

**Comment by sglangevin** [comment]
@garethbowen I'm not able to run those commands without the sudo password for Gardener. Can you or @SCdF help get standard.dev back up and running?

**Comment by garethbowen** [comment]
@sglangevin standard.dev is failing for some other reason (api is running but not receiving requests). I'm looking into it.

**Comment by SCdF** [comment]
I've forward ported our manual buffer-shims addition to master (2.15). Once we hit 3.0 we can drop it again.
