### ISSUE TITLE
Error loading contact view after upgrading to 3.2.0-beta.4

### ISSUE THREAD

**Issue by newtewt** [medic/medic-webapp#5110]
**Steps to reproduce**:
Log in as admin to gamma.dev.medicmobile.org
Navigate to the contacts view
Click on a contact

**What should happen**:
The contact profile is displayed

**What actually happens**:
The translation key for selecting a contact and erroring is shown. contact.select.error. In the console the error below is shown. 

```
inbox.js:3 Error setting selected contact
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
o @ inbox.js:3
a @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
m @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
g @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
n @ inbox.js:3
contact @ inbox.js:3
(anonymous) @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
$apply @ inbox.js:3
(anonymous) @ inbox.js:3
dispatch @ inbox.js:3
m.handle @ inbox.js:3
inbox.js:3 contact.type.district_hospital
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
o @ inbox.js:3
a @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
m @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
g @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
(anonymous) @ inbox.js:3
h @ inbox.js:3
(anonymous) @ inbox.js:3
setTimeout (async)
l.defer @ inbox.js:3
$evalAsync @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
e @ inbox.js:3
o @ inbox.js:3
Promise.then (async)
e @ inbox.js:3
h @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
d @ inbox.js:3
n @ inbox.js:3
contact @ inbox.js:3
(anonymous) @ inbox.js:3
y @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
$apply @ inbox.js:3
(anonymous) @ inbox.js:3
dispatch @ inbox.js:3
m.handle @ inbox.js:3

```

_If this is a problem with the webapp, post the exact URL that has this problem._

https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/ba4d4558-3be0-5600-a24e-dc2c3bf8a08f

**Environment**:

- Instance: gamma.dev
- Browser: Firefox, Chrome, incognito mode all failed
- Client platform: Linux
- App:  webapp 
- Version: 3.2.0-beta.4

I've been seeding and deleting a lot of data. It worked ok before updating through Horti on the master branch. I'm betting it's related but unsure.
